version: '3'
services:
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: uvicorn --host=0.0.0.0 --port=3000 --reload src:app
    volumes:
      - './:/home/viaduct/app'
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
